### ISSUE TITLE
The grader on problem fakecoins always plays as an adaptive one

### ISSUE THREAD

**Issue by dobito6** [Alaxe/interactive-training#1]
I think that the grader never gets the third parameter from the input file, which determines its behavior in the different subtasks, and automatically sets the value of lighter and heavier to -1. Sorry if I have messed something up.

**Comment by Alaxe** [comment]
You're completely right, thank you. I will fix in the next few days (most likely tomorrow).

**Comment by Alaxe** [comment]
The issue has been resolved in 0277e3f2401ca4274a45ca1f89fe4556d4e53cb9.
